# Исключения

Исключения - это ошибки, возникающие в рантайме. 

Для перехвата исключений используется конструкция:

```csharp
try
{
	//код, который может потенциально вызвать исключение
}
catch(Exception ex)
{
	//код по обработке возникшей ошибки
}
finally
{
	//код, который будет выполняться либо сразу после блока try
	//либо сразу после блока catch
}
```

Разберем каждый из этих блоков:

- `try` - здесь мы заключаем код, который потенциально может выбросить исключение;
- `catch` - здесь мы пишем код по обработке конкретного типа исключения. Может быть несколько `catch` -блоков, каждый из который обрабатывает определенный тип исключения;
- `finally` - это опциональный блок. Если он присутствует то код внутри него выполнится в любом случае - вне зависимости от того было выброшено исключение или нет.

Помимо перехвата исключений есть также возможность выброса собственных исключений. Это может пригодиться в следующих ситуациях:

- недопустимое значение аргументов;
- обработка некорректного поведения в логике;
- для валидации при вводе данных от пользователя.

### Основные типы выбрасываемых исключений:

- `ArgumentException` - ошибка аргумента (например, значение < 0);
- `ArgumentNullException` - аргумент является `null`;
- `IndexOutOfRangeException` - ошибка индекса в коллекции (например, попытка обратиться к 4-му элементу массива, который состоит из 3 значений);
- `InvalidCastException` - ошибка преобразования типов.

**Фильтры исключений**

Фильтры исключений позволяют обрабатывать исключения в зависимости от определённых условий. Пример:

```csharp
try
{
	//logic
}
catch(ExternalApiException ex) when (ex.ResponseCode == 404)
{
	//handle error logic
}
catch(ExternalApiException ex)
{
	//handle error logic
}
```

Обработчиком ошибки будет именно тот блок `catch`-блок, для которого истинно `when`-выражение.

### Рекомендации по использованию:

- Использовать правильный проброс исключений
Лучше писать вот таким образом
    
    ```csharp
    try {}
    catch(Exception ex)
    {
    	throw;
    }
    
    ```
    
    Вместо написания:
    
    ```csharp
    try {}
    catch(Exception ex)
    {
    	throw ex;
    }
    ```
    
    В первом случае будет полностью сохранён стек-трейс исключения. Дополнительную информацию можно добавлять в объект `ex`.
    
- Сначала нужно перехватывать наиболее специфичные исключения. Перехват общего `Exception` можно сделать самым последним. При обработке исключений можно попасть только в один `catch`-блок, а не последовательно во все перечисленные.
Как пример, во всех специфичных обработчиках можно выводить конкретные сообщения пользователю, а в обработке общего исключения создавать тикет в службе поддержки, т.к. столкнулись с неожиданным исключением;
- Для специфичных ситуаций нужно реализовывать собственные исключения - это поможет при чтении кода и логов. Также будет легче изучать стек-трейс;
- Нельзя проглатывать исключения. При возникновении любого исключения - его нужно либо логировать, либо корректно пробрасывать его дальше. Нельзя оставлять пустым блок `catch`;
- Вдумчиво выбирайте тип используемого исключения и сообщение для этого исключения. Нужно учитывать, что это сильно ускорит поиск по логам приложения;
- Нужно логировать весь объект исключения целиком, а не только одно сообщение из исключения. Это даст намного более полную информацию при чтении логов;
- Существует 2 способа работы с ошибками:
    - сразу бросать исключение при некорректном поведении (fail fast принцип) - как только происходит ошибочная ситуация - выбрасывать исключение. Плюсом данного подхода является простота и отсутствие обвязок. Не создается никаких лишних абстракций, в случае ошибки сразу выбрасывается исключение. В таких системах создается единая точка обработки исключений, которые перехватывают возникающие исключения и преобразовывают их в корректный вид. Минусом может быть сложность переиспользования отдельных компонентов в другой системе, где единой точки перехвата исключений нет и работа идет с помощью различных оберток;
    - использовать обертки для методов, которые потенциально могут сгенерировать исключения.
    Пример такой обертки - библиотека `OperationResult` (https://github.com/sterlyukin/OperationResult)
    В методе, который потенциально может выбросить исключение, возвращаемый тип указывается как `OperationResult<TType>` и опасный участок кода оборачивается в `try-catch` блок. В случае успешного выполнения метода возвращается `OperationResult.Success` , в случае некорректного - `OperationResult.Fail` . Плюсом данного способа является переиспользуемость - данный код полностью автономен и его можно использовать в любых системах. Он гарантирует, что любые возникающие исключения будут корректно обработаны, залогированы и код продолжит свое выполнение. Минусом является громоздкость данного способа засчет использования абстракций.